apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: skysense
data:
  APP_NAME: "SkySense Frontend"
  APP_VERSION: "1.0.0"
  API_URL: "http://backend-service.skysense.svc.cluster.local:8000"
  WS_URL: "ws://backend-service.skysense.svc.cluster.local:8000"