apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: skysense
data:
  APP_NAME: "SkySense IoT Platform"
  API_URL: "http://192.168.49.2:32180/api"
  WS_URL: "ws://192.168.49.2:32180/ws"
